server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # xxx 换成服务器ip
    url: jdbc:mysql://xxx:6033/dula_template?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    hikari:
      max-lifetime: 900000
      idle-timeout: 600000
      connection-test-query: select 1
  redis:
    # xxx 换成服务器ip
    host: xxx
    port: 6379
    password: 123456
    timeout: 5000
logging:
  level:
    com.crud: info

dula:
  # 是否开启单会话登录
  single-active-session: true
  security:
    # 放行url
    permitAllUrls: /sys/wechat/login, /sys/web/login, /sys/user/password-init, /sys/user/send-verification-code, /sys/user/password-reset-byCode
  api:
    # 是否开启在线接口文档
    online-file: false
  uploader:
    default:
      # xxx 换成服务器ip
      urlPrefix: http://xxx:8088/static/
      # 图片等静态资源路径
      storagePath: /opt/services/data/
